### ISSUE TITLE
did you try to reproject points to depth image?

### ISSUE THREAD

**Issue by lzcchl** [CyanJoeng/panoptic-dataset-tools#1]
Hi, I use your code for show rgb image very well, but when I try to reproject points to depth image, it seems some offset just like picture below.
and I find that why "K_color"/"distCoeffs_color" in kcalibration_171204_pose1.json is different from "K"/"distCoef" in calibration_171204_pose1.json, what mean of these? why there are different?
![](https://user-images.githubusercontent.com/34515022/173734355-ce2becf8-d49b-4709-9c12-aa1cc8d02690.png)

![](https://user-images.githubusercontent.com/34515022/173734373-1d3e972d-4e8e-4728-8ae4-58b2ada4877a.png)

**Comment by CyanJoeng** [comment]
Hi, lzcchl
Thank you for using this project.
For the first question, you found that CMU panoptic is not a high precise dataset.
For the second one, they are not the same camera, the hardware structure of the PanopticStudio should have known, and it can be found on the official website.

By the way, https://arxiv.org/pdf/1612.03153.pdf this may be helpful. Good luck 👍
